server:
  port: 8080
spring:
  application:
    name: tracepoint-c
  config:
    import: "optional:file:.env[.properties],optional:vault://"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: core
    hibernate:
      ddl-auto: update
  cloud:
    vault:
      host: ${VAULT_HOST}
      port: ${VAULT_PORT}
      authentication: TOKEN
      token: ${VAULT_CONFIG_TOKEN}
      kv:
        enabled: true
        backend: ${VAULT_MOUNT}
        application-name: ${VAULT_PATH}
      # ssl:
      #   trust-store: classpath:${TRUSTSTORE_PATH}
      #   trust-store-password: ${TRUSTSTORE_PASS}